name: Integrations Tests

on:
  push

jobs:
  test:
    name: Integration Tests
    runs-on: ubuntu-latest
    env:
      TEST_DATABASE_HOST: '127.0.0.1'
      TEST_DATABASE_PORT: '8888'
      TEST_DATABASE_NAME: integration_test
      TEST_DATABASE_USER: root
      TEST_DATABASE_PASSWORD: password
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: integration_test
        ports:
          - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v5

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          ini-values: memory_limit=1024M

      - name: Install npm Dependencies
        run: npm install

      - name: Fetch EspoCRM
        run: |
          node build --fetch
          node build --composer-install

      - name: Build EspoCRM Test Instance
        run: |
          cd site
          npm install
          npx grunt test

      - name: Run Tests
        run: npm run test-integration
