name: Unit Tests

on:
  push

jobs:
  test:
    name: Test on PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          ini-values: memory_limit=1024M

      - name: Install npm Dependencies
        run: npm install

      - name: Install Composer Dependencies
        run: |
          node build --fetch
          node build --composer-install
          cd site
          composer update --no-interaction --dev

      - name: Run Tests
        run: npm run test-unit
